name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Navigate to project directory
      working-directory: on-exit-hook-waybar
      run: echo "Navigated to on-exit-hook-waybar directory"

    - name: Build
      working-directory: on-exit-hook-waybar
      run: cargo build --verbose

    - name: Run tests
      working-directory: on-exit-hook-waybar
      run: cargo test --verbose
